server:
  port: 8090
spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/jzy_cxkj
    username: root  
    password: 1234  
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-wait: 10000
    min-idle: 5
    initial-size: 5
        
mybatis:
  mapper-locations: classpath*:com/preferential/panning/*/mapper/*.xml
    
    